### DISCUSSION TITLE
New CUDA version

### DISCUSSION THREAD

**Discussion by kaixxx** [kaixxx/noScribe#50] [Announcements]
I've compiled a new version that should support acceleration via NVIDIA graphics cards using cuda. It's not officially released yet. Could you test and report back if it works? Thanks!
Installer here: https://drive.switch.ch/index.php/s/EIVup04qkSHb54j?path=%2FnoScribe%20vers.%200.4.5%2FWindows%2Fcuda%20version

**EDIT (09.04.2024): It appears to function quite well. Here are some tips gathered from the discussion below:**
- You must install the [CUDA toolkit from here](https://developer.nvidia.com/cuda-downloads?target_os=Windows) (a reboot is required afterward). If your graphics card isn't supported, consider installing [CUDA 11 from this location](https://developer.nvidia.com/cuda-toolkit-archive).
- A user noted that 4GB of GPU memory may not suffice for running the 'precise' transcription model. Should you encounter an 'out of memory' error while transcribing, you may still be able to utilize the GPU during the speaker detection phase. To achieve this, navigate to the "config.yml" file located at "C:\Users\<USERNAME>\AppData\Local\noScribe\noScribe" and set "pyannote_xpu" to "cuda" and "whisper_xpu" to "cpu" (omit the quotes).
- With a powerful graphics card that has ample memory, you might be capable of running multiple instances of noScribe concurrently, transcribing various audio files simultaneously.

**Comment by amru39** [comment]
I did not have any trouble in installing or starting the process of generating a transcript (CPU usage remained below 20%). The file I tried was not in English and I faced the issue you listed in known issues (loop of repeating text) after the 10th minute in a 30 minute audio file.

**Reply by kaixxx** [reply]
Thank you for testing, sounds promising!
The phenomenon of looping text is a little annoying, it can happen in any language. I'm thinking about implementing a detection algorithm to at least stop and restart the transcription if this happens.

**Comment by Lod3** [comment]
> I've compiled a new version that should support acceleration via NVIDIA graphics cards using cuda. It's not officially released yet. Could you test and report back if it works? Thanks! Installer here: https://drive.switch.ch/index.php/s/EIVup04qkSHb54j?path=%2FnoScribe%20vers.%200.4.5%2FWindows%2Fcuda%20version

Any special specific install instructions on how to install and try this version?

**Reply by kaixxx** [reply]
No, you can just install it like normal. 
If the window appears "Previous version of noScribe found. Do you want to remove it first (recommended)?", I would click on "Yes" so that you get a fresh and clean install.
You can always re-download the last version if this new one doesn't work for some reason.

**Reply by Lod3** [reply]
I removed the previous installation. Downloaded the two files you linked installed the new version. Installed noscribe again.
Do I need to do anything with the noScribe_setup_0_4_5_cuda.nsisbin file? 
Because I just tested it but the GPU is not being used much, the CPU is 90% 
![image](https://github.com/kaixxx/noScribe/assets/14292591/7eff8740-c009-4688-b583-f0188fc4a1c1)

**Reply by kaixxx** [reply]
> Do I need to do anything with the noScribe_setup_0_4_5_cuda.nsisbin file?

No, this file is used automatically during the installation.

> the GPU is not being used much

Yes, it seems that it is not yet fully working. It may be that noScribe is not picking up the cuda libraries. Please follow these two steps:
- Add this to your PATH variable in Windows: "C:\Program Files (x86)\noScribe\torch\lib" (if you installed noScribe in the default location, otherwise change the path accordingly). If you don't know how to change PATH, look here: https://techpp.com/2021/08/26/set-path-variable-in-windows-guide/
- Check the contents of the file "config.yml" in "C:\Users\<USERNAME>\AppData\Local\noScribe\noScribe": Both "pyannote_xpu" as well as "whisper_xpu" should be set to "cuda".

**Reply by kaixxx** [reply]
small addition: Please change "config.yml" only when noScribe is closed.

**Reply by gernophil** [reply]
@Lod3: could you share the output of your `nvidia-smi`? Here's a manual how to run it in windows. It should state driver and cuda versions: https://stackoverflow.com/a/57100016/16611809

**Reply by Lod3** [reply]
@gernophil thanks, I figured something was wrong with the CUDA drivers so I reinstalled them on my desktop. Seems to work now
@kaixxx it is working beautifully this is amazing. What yaml file do I edit? The noscribe.en.yml file? Can I crank it a bit more so it goes even faster? 😁 
![firefox_upjTbjtnQw](https://github.com/kaixxx/noScribe/assets/14292591/1d652db0-64a6-482a-a24a-e9fbf82ad7bb)
I feel like I have to tell you, we (my colleague and I from meemoo.be) have tested a whole bunch of speech to text applications free and commercial. For small heritage organisations this could become such a boon to transcribe valuable interviews about immaterial cultural heritage or presentations to preserve knowledge, thank you. We have some feedback about things I shall leave them under feature requests in the issues. If you want to have them in another way let me know.

**Reply by kaixxx** [reply]
Nice! If the animated gif shows the transciption in realtime, that's pretty fast - especially given the fact that you use the 'precise' model and a mid-level graphics card. 

>  What yaml file do I edit? 

The "config.yml" is in `C:\Users<USERNAME>\AppData\Local\noScribe\noScribe`. You can check if both values mentioned above are set to "cuda". But I'm pretty sure they are because it's working so well now.

>  I figured something was wrong with the CUDA drivers so I reinstalled them on my desktop

Could you please make a simple writeup on how to find and install these drivers for a particular card? I would like to integrate that in the readme for other users in the future.

Nice to hear that this is working so well for your interesting application. If you have feature ideas, feel free to create an issue!

**Reply by gernophil** [reply]
I think, if you simply install the latest Nvidia drivers for you card it should be fine. CUDA should be bundled with them. And using nvidia-smi you can check your cuda version.

**Comment by kaixxx** [comment]
@vBodrov reported in another thread:
> Tried it with GTX 1050 Ti 4Gb, have failed on «transcribe» phase with «out of memory error». I haven't had time to tinker with it yet, so I'll try again this week.

Interesting. There is a good chance that 4GB of VRAM are not sufficient for the large whisper model. You can try the "fast" setting in noScribe. This will use a much smaller model. The quality is not great. But this would confirm that in fact the size of the model is the problem.

**Comment by Lod3** [comment]
> Nice! If the animated gif shows the transciption in realtime, that's pretty fast - especially given the fact that you use the 'precise' model and a mid-level graphics card.
> 
> > What yaml file do I edit?
> 
> The "config.yml" is in `C:\Users<USERNAME>\AppData\Local\noScribe\noScribe`. You can check if both values mentioned above are set to "cuda". But I'm pretty sure they are because it's working so well now.
> 
> > I figured something was wrong with the CUDA drivers so I reinstalled them on my desktop
> 
> Could you please make a simple writeup on how to find and install these drivers for a particular card? I would like to integrate that in the readme for other users in the future.
> 
> Nice to hear that this is working so well for your interesting application. If you have feature ideas, feel free to create an issue!

It's really simple

- go here https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local

- click the Windows button here https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=11

- And download the correct version for you system, Windows 10, 11 or server.

- Click local (offline) or network (online-only) installer 

- Click the "Download" button that appears.

- Follow installer instructions, next, next, etc.

- Reboot

Done

> I think, if you simply install the latest Nvidia drivers for you card it should be fine. CUDA should be bundled with them. And using nvidia-smi you can check your cuda version.

The gif from earliers is from my desktop 

this is the result from the laptop on which I tried transcribing earlier with the latest drivers installed 

```
Mon Mar 18 13:45:22 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.76                 Driver Version: 551.76         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   46C    P8              5W /   65W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      9612    C+G   ...ekyb3d8bbwe\WsaClient\WsaClient.exe      N/A      |
+-----------------------------------------------------------------------------------------+
```

![image](https://github.com/kaixxx/noScribe/assets/14292591/2f53c413-66cd-4086-a206-35c25adf8ccf)

I would still need to install the CUDA drivers like I mentioned above because I just tested it and noscribe on the laptop does not use the GPU when transcribing.  I just tested it again. I am going to install the CUDA drivers now and report back :) 

The laptop config 
![image](https://github.com/kaixxx/noScribe/assets/14292591/92e278dd-8b23-4f82-88f4-4e9fbe7662d1)

**Reply by Lod3** [reply]
hmmm maybe cuda its not supported on this GPU 🤔 pitty
![setup_TBofgIm3Jy](https://github.com/kaixxx/noScribe/assets/14292591/6de1f3db-fede-410f-af98-83b610f17f26)

**Reply by kaixxx** [reply]
Is the first step (speaker identification) using your GPU, at least to some extend? This would suggest that cuda is working and we only need to point faster-whisper to right libraries. 
We are using cuda 11 in noScribe, not vers. 12 that you tried to install. Vers. 12 should be backwards compatible, but maybe your graphics card is no longer supported in 12 but still in 11. The RTX 2060 is not that old.

**Comment by paskima** [comment]
Thanks! Works like charm for me! [Die Schatzinsel](https://www.ohrka.de/hoeren/tierisch-spannend/die-schatzinsel) (342 min) works for me on  
RTX_4090 (24GB VRAM, used mostly ~10GByte)- 293 min
RTX_1070_TI (8GB VRAM)- 453 min
RTX_A500 (4GB VRAM) -  >600min (but uses cuda!)

(But i think, I installed Cuda by myself before on all three Systems)
 
Also diarizing used cuda. Just typical small bugs (setting rights on win11, language on auto -> always translating to english automatically) 

Speech-Translate (https://github.com/Dadangdut33/Speech-Translate (also faster whisper)) did not work on laptop w/ RTX_A500

**Comment by mohammedalsayegh** [comment]
I tested it with 2060 super. It works with both diarization with PyAnnote and whisper.
![image](https://github.com/kaixxx/noScribe/assets/40126750/6fac481f-44ec-42e3-9c69-1f3c072f76c7)

I am running it under widnwos 11 with 
```
 nvidia-smi
Sun Mar 24 20:27:37 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.86                 Driver Version: 551.86         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2060 ...  WDDM  |   00000000:08:00.0  On |                  N/A |
| 27%   47C    P8             20W /  175W |     834MiB /   8192MiB |      7%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

**Comment by antonioaraujo664** [comment]
![WhatsApp Image 2024-03-28 at 14 05 54_6fdaef37](https://github.com/kaixxx/noScribe/assets/16484533/fd9624d0-62a8-4bb4-be01-5b5a3f45c888)

it works!
Being able to run 4 programs at the same time. (RTX 3060 12GB)


I will make some suggestions that will be useful

1.Upload video in batch.

2. Possibility of running on Tensor Cores on RTX cards


As soon as I have some time to do a comparative test CPU Xeon 14 cores 128 GB RAM vs 3060 12gb


THANKS!

**Comment by Aloks6** [comment]
Thank you very much for this release !

On my side, it did work better (went from 19mn to transcribe 5mn audio to 4-6mn), and it seems the GPU is working to some extent.
Though when checking the task manager, it doesn't seem the GPU is working much. It got one peak at 100% when pyannote was embedding, then cap at 5%. 
CPU on the other side works sometimes at 100%
CUDA is installed, and I tried to reinstall it but nothing changed. 

Also checked the yml file, everything is correct. I also added the PATH. 

![image](https://github.com/kaixxx/noScribe/assets/159426567/0b8bfc91-2721-43f5-92cd-83a324b86836)

```
Fri Mar 29 15:52:35 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.86                 Driver Version: 551.86         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...  WDDM  |   00000000:05:00.0 Off |                  N/A |
|  0%   40C    P8             12W /  285W |     629MiB /  16376MiB |      3%      Default |
|                                         |                        |                  N/A |

```

Thank you for your help !

**Reply by kaixxx** [reply]
Thanks for testing!

> went from 19mn to transcribe 5mn audio to 4-6mn

This is quite an improvement so the GPU must work harder than shown in the screenshot. Can you check if it is used during the transcription phase? My guess is that pyannote is not using the GPU all that well, but faster-whisper does. I may need to update pyannote, there is a new version out.

**Reply by Aloks6** [reply]
Well using windows task monitor, it stays the same both during annotation and transcription. 
I used HWInfo to get more precise results and it seems the GPU is sometimes working hard (around 80%), but most of the time it isn't :( 

With windows task monitor during transcription : 
![2024-04-02 09_22_50-](https://github.com/kaixxx/noScribe/assets/159426567/2ba53bb8-a7eb-4284-b0f4-7de7d51655a5)

With HWInfo : 

Pyannote : 
![2024-04-02 09_43_10-noScribe - Transcription audio alimentée par l'IA](https://github.com/kaixxx/noScribe/assets/159426567/8b4cd3c3-8244-445b-ac82-ab0b11ab702f)

Transcription : 
![2024-04-02 09_44_07-noScribe - Transcription audio alimentée par l'IA](https://github.com/kaixxx/noScribe/assets/159426567/36023960-2401-4db6-88b6-c5a3d5954c6b)

And the peak use (CUDA) : 
![2024-04-02 09_44_44-noScribe - Transcription audio alimentée par l'IA](https://github.com/kaixxx/noScribe/assets/159426567/79a4f592-bade-4d21-92fe-41f433cf54eb)

But as I said, it seems to work randomly. Most of the time the GPU use is close to 0%.
Can the issue be on my side ? 

Thanks for the answer :)

**Reply by kaixxx** [reply]
The transcription is a complex process, consisting of many steps. Only some of them can be accelerated by the GPU, others must run on the CPU. Your imporvements in overall transcription time are quite impressive. I think this is the maximum we can do at the moment. 

The only option would be to run several instances of noScribe in parallel, like @antonioaraujo664 did above: https://github.com/kaixxx/noScribe/discussions/50#discussioncomment-8943492 At some point, you will run out of GPU-memory though.

**Comment by JB-FHE** [comment]
The 0.4.5 Cuda Version runs like a charm and the quality of transcription results compete with amberscript. Thanks a lot for this release, the CUDA acceleration gains a big performance boost.
I've tested this release on two different workstations with an interesing insight: 

**The CUDA transcription speeds scales massive with RAM speed/timings/bandwith.**

System 1: Intel i7-13700k, 16GB DDR5-4400 CL36 RAM (One Module - **single channel**), NVidia RTX4070
10 Minute interview file -> transcription duration 4 minutes (overlapping speech, precise) 

System 2.1: AMD Threadripper1950x, 32GB DDR4-2133 CL15 (Four Modules - **quad channel**), NVidia RTX4070  
10 Minute interview file -> transcription duration 3 minutes (overlapping speech, precise) 

System 2.2: AMD Threadripper1950x, 32GB DDR4-3600 CL17 (Four Modules - **quad channel**), NVidia RTX4070  
10 Minute interview file -> transcription duration 1 minute (overlapping speech, precise) 

Maybe this should be mentioned in the recomended hardware section, I've spend some hours to get it why the much recent Intel system is much slower than our old Threadripper workstation.

**Reply by kaixxx** [reply]
Interesting observation regarding the RAM speed. I think I will compile a separate document with all the information about hardware, drivers etc. for a fast cuda based system (I've already started to edit my initial post above). 

Overall, your numbers are very impressive. Is this with speaker detection on? Have you also tried running multiple instances in parallel like antonioaraujo664 (https://github.com/kaixxx/noScribe/discussions/50#discussioncomment-8943492)?

BTW, do you plan running noScribe on a server? A collegue from the University of Jena is in the process of developing a client-server version. I hope this will be ready within the the next few months.

**Reply by JB-FHE** [reply]
Speaker detection was on.
I've done some more testing with inputfile: [Die Schatzinsel](https://www.ohrka.de/hoeren/tierisch-spannend/die-schatzinsel) (**342 min**) like paskima (https://github.com/kaixxx/noScribe/discussions/50#discussioncomment-8876068)

**_[Test 1]_** running a **single instance** of noScribe
System 1.1: Intel i7-13700k, 16GB DDR5-4400 CL36 RAM (One Module - **single channel**), NVidia RTX4070
transcription duration: **331 minutes** (precise, speaker detection on) 
System 1.2: Intel i7-13700k, 32GB DDR5-4400 CL36 RAM (Two Modules - **dual channel**), NVidia RTX4070
transcription duration: **176 minutes** (precise, speaker detection on) 
System 2: AMD Threadripper1950x, 32GB DDR4-3600 CL17 (Four Modules - **quad channel**), NVidia RTX4070  
transcription duration: **140 minutes** (precise, speaker detection on)   

![Schatzinsel single](https://github.com/kaixxx/noScribe/assets/166630789/951b0382-e3e5-4fbc-bc47-45670fedc12a)  


**_[Test 2]_** running **3 multiple instances of noScribe in parallel** like antonioaraujo664 (https://github.com/kaixxx/noScribe/discussions/50#discussioncomment-8943492) 
System 2: AMD Threadripper1950x, 32GB DDR4-3600 CL17 (Four Modules - **quad channel**), NVidia RTX4070 
transcription duration: **204 minutes** (precise, speaker detection on)
median GPU usage 90% ! but I think memory bandwidth and CPU limitation kicks already in while the "embeding" and "loading pyannote" phases, CPU load is low while "whispering".

Indeed, we're planning to run noscribe on a server, so server/client development would be perfect! 
BTW I work for the university of applied sciences in Erfurt ;-)     

![Schatzinsel multi 5](https://github.com/kaixxx/noScribe/assets/166630789/b3dcbc1f-cde2-4b56-8f57-1a0d751c8a33)
![Schatzinsel multi](https://github.com/kaixxx/noScribe/assets/166630789/a8eb55ef-5676-45b6-b77e-51280b725c81)

**Reply by kaixxx** [reply]
Thank you for this systematic testing, that's very helpful. 
So the best you got in single mode was **0.4 x RT (Real Time)** (144/342)
Running three instances in parallel gives you **0.2 x RT**  (204/(3*342))

This is a little slower than your initial test with the shorter interview suggested, but still a very good result. 

@eckhrd is the one who is going to work on the client/server version soon. You may ask him if he needs help...

**Reply by JB-FHE** [reply]
I've done a RAM upgrade on the i7-13070K Workstation **Single->Dual Channel**,
as predicted the transcription time droped arround 50%, **331->176 minutes**.
Disabling the efficency cores also gains a performance boost (Windows hybrid CPU scheduling is still complicated).
For server hardware (smoothly capable of handling _**four simultaneous noScribe Tasks**_) I would recommend a octa channel RAM build with 12 or 16-Core CPU and a graphics card with 16GB GPU Memory.
(i.e.):
Lenovo ThinkStation P7 (Xeon w5-3435X, 8x16GB DDR5-4800, RTX 4070Ti Super/4080)
Lenovo ThinkStation P620 (Ryzen Threadripper PRO 5945WX, 8x16GB DDR4-3200, RTX 4070Ti Super/4080)
Lenovo ThinkStation P8 (Threadripper PRO 7945WX, 8x 16GB DDR5-5200, RTX 4070Ti Super/4080)

**Reply by gernophil** [reply]
I didn't know these efficiency cores are a thing with windows, too. For macOS I only use the performance cores, which i get using `sysctl -n hw.perflevel0.logicalcpu_max`. Maybe there is a similar command for windows instead of `cpufeature.CPUFeature["num_physical_cores"]`.

**Comment by antonioaraujo664** [comment]
Each instance consumes an average of 3.5 GB of VRAM. On the 3060 12gb there are times when the machine freezes with three. 

Any plans to get batch processing one by one in order?
I wanted to leave the computer transcribing several videos over the weekend

**Reply by kaixxx** [reply]
Yes, batch processing is high on my list. But it may still take a while until it becomes reality. As mentioned above, we are working on a client/server version. This needs some restructuring of the code which will also make batch-processing much easier to implement. We have to take it step by step.

**Reply by JB-FHE** [reply]
Have you tried to install the Nvidia Geforce "Studio" Driver?
[->**Nvidia Studio Driver Download**](https://www.nvidia.com.br/content/DriverDownloads/confirmation.php?url=/Windows/552.22/552.22-desktop-win10-win11-64bit-international-nsd-dch-whql.exe&lang=br&type=GeForce)
[->**Nvidia Studio Driver Download (Notebook GPU)**](https://www.nvidia.com.br/content/DriverDownloads/confirmation.php?url=/Windows/552.22/552.22-notebook-win10-win11-64bit-international-nsd-dch-whql.exe&lang=br&type=geforcem)

These Drivers are more stable than the "Game Ready" Drivers. 
You should be able to run 3 parallel noScribe instances.

**Comment by jad969** [comment]
Hello! This new version is running super smooth on my computer compared to the previous version of noScribe. Before, noScribe would freeze while it was transcribing and it was really terrifying but it always got the transcription done. I only had that weird repeating word issue happen once. This new version can run in the background while I do other work so big fan! I'm running an old Alienware from 2016 with a GTX 1060. Thanks again for making my PhD life easier!!

**Reply by kaixxx** [reply]
Nice to hear that even older computers may benefit from this. You have 6 GB of VRAM, right? That seems to be the minimum.

**Reply by jad969** [reply]
Yes! Can confirm 6 gb of vram.

**Reply by jad969** [reply]
I've gone through a few files now and am running up against the repeating word loop thing way more than with the old version. Any suggestions for adjustment of settings that could help this? Before the word loop the transcription is very good!

**Reply by kaixxx** [reply]
Strange that this occurs more often now, it should be absolutely the same. Maybe it just feels more often because the transcription is so much quicker now?
Anyhow, there is not much you can do. You can restart the transcription from the point where the loop starts and combine the two files later. To find out the exact timestamp, open the transcript with the loops in the editor. In the bottom right corner you'll see the timestamp of the text currently under the cursor. I think about automating this somehow in a future version. 
If you would be running noScribe from source, you could try another option. But I doubt that it would help much, so probably not worth the hassle.

**Reply by jad969** [reply]
Listened a little more carefully to when the word loop starts because it has been at very specific points in my audio files. It seems that there was some glitchy silence in both of the points where the word loop started. In one instance the silence was maybe about 13ish seconds long. In the other instance there was a few seconds of glitchy silence and then the interviewee continued to speak while the glitchiness continued for a few more seconds. I can't be 100% sure that its the glitchiness but then again, the word loops only happen there? Hope this helps! Like you suggested above, I just restarted the transcription from just after the word looping point and all is good.

**Reply by kaixxx** [reply]
I've made the same observation: If there is a silent part with some background noise, whisper may start to hallucinate text which can then result in a loop. Maybe a VAD filter would help to filter these silent parts out - something to test for the future.

**Comment by mohammedalsayegh** [comment]
I observed a very strange behaviour in the GUI that led to an increase in the speed of the embedding and segmentation process by approximately 50%. For some reason, when minimizing and maximizing the NoScibe window during the embedding and segmentation part, it appears to utilize more cores and result in a time reduction of roughly half.

I tested this with a 15-minute audio file, comparing waiting versus minimizing and maximizing the NoScibe window. The results were striking: it took 6 minutes to wait for the process to complete vs. just 3 minutes when toggling the NoScibe window. Initially, I thought that Python's buffering might be slow and only load the UI when in focus, but the time difference tells a different story.

**Reply by mohammedalsayegh** [reply]
![image](https://github.com/kaixxx/noScribe/assets/40126750/5e35072c-02dc-4c49-9977-97eba5ffb540)

**Reply by JB-FHE** [reply]
Wow, this is really getting weird now. I've tested "minimizing and maximizing the noScibe window during the embedding and segmentation part" (on our Core i7-13700K build running **Windows 11**) with no significant difference. But if I open the Windows task manager and don't close it, the transcription speed is hilarious faster on this system. Even my single/dual/quad Channel conclusions (https://github.com/kaixxx/noScribe/discussions/50#discussioncomment-9096192) and hardware recommendations (https://github.com/kaixxx/noScribe/discussions/50#discussioncomment-9127987) seems to be obsolete now.

 Inputfile: [Die Schatzinsel](https://www.ohrka.de/hoeren/tierisch-spannend/die-schatzinsel) (**342 min**) 

**_[Test 1]_** running a single instance of noScribe with **Windows Task manager active/on focus**
System 1.1: Intel i7-13700k, 16GB (One Module - **single channel**), NVidia RTX4070
transcription duration: **55 minutes** (precise, speaker detection on) 
System 1.2: Intel i7-13700k, 32GB (Two Modules - **dual channel**), NVidia RTX4070
transcription duration: **54 minutes** (precise, speaker detection on)

**_[Test 2]_** running a single instance of noScribe with **NoScribe minimized to the Taskbar** 
System 1.2: Intel i7-13700k, 32GB DDR5-4400 CL36 RAM (Two Modules - **dual channel**), NVidia RTX4070
transcription duration: **440 minutes** (precise, speaker detection on)

Being observed forces the KI to work harder/faster?!?.
I couldn't reproduce this behaviour on the Threadripper system running Windows 10 (it is even slower), maybe this is an **Windows 11 issue**?


![Screenshot 2024-04-24 084450_Taskmanager active_Singel Channel](https://github.com/kaixxx/noScribe/assets/166630789/48310f7c-d9aa-42fb-aae2-6f5a92c4ff11)
![Screenshot 2024-04-24 084450_Taskmanager active_Singel Channel_result](https://github.com/kaixxx/noScribe/assets/166630789/ecd98ec8-460c-43b8-9a57-21f8690dfa4d)

**Reply by gernophil** [reply]
I wonder, if this is an effect of the `customtkinter` GUI. We don't have a GUI independent version yet, do we?

**Reply by kaixxx** [reply]
> Being observed forces the KI to work harder/faster?!?

The disciplinary power of surveillance! Foucault was right... (sorry for this social-sciences-insider)

> I wonder, if this is an effect of the customtkinter GUI. We don't have a GUI independent version yet, do we?

No CLI-version yet, no. 

This is really weird. I'm wondering if Windows 11 is doing some form of throttling by limiting CPU or GPU utilization if an app is minimized to the taskbar? This theory is based on the assumption that in your first test, noScribe was still visible on the screen and updating its window, just partially hidden by the task manager. But maybe I'm misinterpreting your screenshot here.

**Reply by mohammedalsayegh** [reply]
I'm not sure, but it might be more related to the system promoting printouts rather than the Tk library itself. It could be a result of how Windows 11 handles printouts, causing it to only utilize printouts from Tk when it is in focus, which slows down the rest of the process. It doesn't make much sense, but I noticed it in one of my projects: using real-time printouts caused a huge overhead, but when I redirected them to a text file to avoid Python handling the system printout, there was a significant increase in performance. However, I'm not entirely sure if this is the case here.

**Reply by gernophil** [reply]
Isn't `embeddings` and `segmentation` part of the outsourced `diarize.py`? Then we should indeed be able to test this without the Tk GUI.

**Reply by mohammedalsayegh** [reply]
So, I run few tests today, here is the results:
| Test Description                      | Elapsed Time           |
|---------------------------------------|------------------------|
| Tested with audio 43:12 in length    |                        |
|                                       |                        |
| With CUDA                             |                        |
| - Windows (on focus)                  | 00:01:37.0153326      |
| - Windows (minimized)                 | 00:01:20.0092037      |
|                                       |                        |
| Test with SimpleProgressHook removed | 00:01:18.0126752      |


This is the PowerShell script that I used to measure the time of `diarize.py`:
```powershell
# Record the start time
$startTime = Get-Date

# Run the Python script in a new window
Start-Process -FilePath "python" -ArgumentList "diarize.py", "cuda", ".\tmp_audio.wav", "out.yaml" -NoNewWindow -Wait

# Record the end time
$endTime = Get-Date

# Calculate the elapsed time
$elapsedTime = New-TimeSpan -Start $startTime -End $endTime

# Print the elapsed time
Write-Output "Elapsed Time: $elapsedTime"
```

But the difference that was spotted in the GUI was higher. So, I will revert my assumption that it is a printing issue, and it could be a Tk library thing.

**Reply by kaixxx** [reply]
Did some tests on my AMD Ryzen AMD 7 6800U mobile processor, no cuda. 
**I do get consistently around 20% better results (shorter time) if the noScribe is visible vs. it beeing minimized.** This is for the full process, not only diarize.py. I had speaker identification on and was using the 'precise' model. ​Having the task manager running or not did not make any difference. 

I'm pretty sure this has to do with Windows 11 prioritizing foreground processes to 'improve user experience', see: https://superuser.com/questions/1763751/windows-10-11-cpu-performance-lowers-to-half-when-computational-task-is-not-in-f
I've tried turning this off via `powercfg /powerthrottling disable /path "path to noScribe"`, but did not see a significant difference. However, since I'm running noScribe from source it was a little difficult to find the right process to disable the powerthrottling. It may be worth investigating this more with the compiled version of noScribe.
BTW, i've also tried raising the process priority to 'realtime' in the task manager for the minimized process. Made no difference either.

**Reply by JB-FHE** [reply]
In my case, to gain full speed the Windows Taskmanager or an other app (tested with Firefox) has to stay open and on focus.
If I close, minimize the Taskmanager/Firefox window or set the window focus on the noScribe window the transcribing speed goes instand down (at any stanges of the transcription process).

**Full Speed:** noScribe Window open, Taskmanager/Firefox window on focus
Reduced Speed: noScribe Window open and on focus, Taskmanager/Firefox not on focus
Reduced Speed: noScribe Window open and on focus, Taskmanager/Firefox minimized
Reduced Speed: noScribe Windows minimized to Taskbar, Taskmanager/Firefox on focus

**Reply by JB-FHE** [reply]
Forgot to mention: 
The efficiency cores are disabled on the testsystem, so the problem is not related to Windows handling of the efficiency cores (unloading non foreground tasks to e-cores only). Changing the prozess priority to "Real time" doesn't help easer.

**Reply by mohammedalsayegh** [reply]
It gets a bit stranger. Today, while using noScribe, I noticed that when the noScribe window is open and in focus during the faster whisper part, and when **I move the mouse in a circular motion** during the text generation part, it parses faster compared to when the noScribe window is open and in focus.

So it's not just a matter of being in focus or out of focus, but also how the mouse interacts with the running software UI. I haven't tested it with a laptop-grade CPU yet. My tests were conducted on an AMD 3700x and an Intel 2699v3, both of which are desktop-grade CPUs. So, I don't think that it's related to the E-cores in Intel or the energy-efficient cores in AMD.

**Reply by mohammedalsayegh** [reply]
Here's how I tested it: It seems that interacting with the widget of the Tkinter UI causes the most significant increase in speed. I used PyAutoGUI to hover in a circular motion around the audio file select folder widgets, and it caused a huge increase in speed. 

https://github.com/kaixxx/noScribe/assets/40126750/d7398636-a890-4bb3-b86c-00f203d66dbc

**When running the script, please be aware that it locks the mouse in a circular motion within specific coordinates for 60 seconds. The only way to exit is by keeping the terminal open and pressing Ctrl+C to quit or using Ctrl+Shift+Del to force interruption.**

```python
import pyautogui
import time
import math

# Display warning message
print("WARNING: This script will lock the mouse in circular motion in the 200 x 250 coordinates for 60 seconds.")
print("The only way to exit is by keeping this terminal open to press Ctrl+C to quit or Ctrl+Shift+Del to force interruption.")
print("Please ensure that you are running this script intentionally.")

# Define the center and radius of the circular motion
center_x = 200  # Update with the x-coordinate of the center of your window
center_y = 250  # Update with the y-coordinate of the center of your window
radius = 50  # Adjust the radius as needed

# Define the duration for which the script will run (in seconds)
duration = 60  # Adjust as needed

# Define the number of steps to complete the circular motion
num_steps = 15  # Adjust as needed

# Calculate the angle increment between each step
angle_increment = 2 * math.pi / num_steps

# Track the start time
start_time = time.time()

try:
    while time.time() - start_time < duration:
        for i in range(num_steps):
            # Calculate the angle for this step
            angle = i * angle_increment
            # Calculate the coordinates of the point on the circle
            x = center_x + radius * math.cos(angle)
            y = center_y + radius * math.sin(angle)
            # Move the mouse cursor to the calculated coordinates
            pyautogui.moveTo(x, y)
            # Wait for a very short duration before the next step
            time.sleep(0.001)  # Adjust as needed for faster motion
except KeyboardInterrupt:
    # Stop the script if Ctrl+C is pressed
    pass
```

**Comment by kaixxx** [comment]
Hello

A new version of noScribe (0.6) is ready with a lot of improvements, but we are still ironing out some issues with Mac. 
In the meantime: **Could some of you please test the new version with CUDA?** This would be great. 
Download for Windows: https://drive.switch.ch/index.php/s/HtKDKYRZRNaYBeI

I can't test it myself since I don't have NVIDIA graphics in my system. What irritates me a little is the fact that the compiled version with cuda is now about the same size as the non cuda version. I hope that everything is included correctly. 

The new version should be much faster overall. On CPU, I see a 3 to 5 times speed improvement in the transcription phase. I'm curious if this is the same with cuda. 
Also, the new version should remedy the very strange issue that @mohammedalsayegh observed above, see https://github.com/kaixxx/noScribe/issues/105

**Reply by JB-FHE** [reply]
I Updated Version 0.5 -> 0.6 
Version 0.6 shows the folling error:
"PayAnnote error: Torch not compiled with CUDA enabled" (Speaker detection task)

![Torch not compiled](https://github.com/user-attachments/assets/8e709ea7-b23c-4c5c-8eed-a740955a4725)

**Reply by kaixxx** [reply]
Thank you very much. So, my suspicion was right, the CUDA-libraries are not included properly. Give me a little time, I will compile and upload a new version.

**Reply by kaixxx** [reply]
A new version is available under the same link:  https://drive.switch.ch/index.php/s/HtKDKYRZRNaYBeI
I hope it works now. You need both files for the installation. Please give it a try! Thanks a lot.

**Reply by paskima** [reply]
Awesome! No Mouse-Moving or other special tricks anymore! On Nvidia RTX 4090 ~1h Audio pyannoted  & transcribed in <12 minutes... And working at the same time on something else... THANKS!

**Reply by kaixxx** [reply]
@paskima: Thanks, sounds nice!

**Reply by JB-FHE** [reply]
@kaixxx I've tried the new V0.6 build again. The "Torch error" is fixed but no speed improvement.

V0.6 on focus: 155 Minutes
V0.6 with Firefox window on focus: 145 Minutes
V0.5 with Firefox windows on focus: 49 Minutes

inputfile: [Die Schatzinsel](https://www.ohrka.de/hoeren/tierisch-spannend/die-schatzinsel) (342 min)
Intel i7-13700k, 16GB DDR5-4400, NVidia RTX4070 

![Screenshot 2025-01-23 121730_V0_6_No Firefox Focus](https://github.com/user-attachments/assets/58fdaa61-b736-41cb-9efa-808b31fc1c73)
![Screenshot 2025-01-24 V0_5 Firefox Focus](https://github.com/user-attachments/assets/9388be58-0a82-4665-b6c9-8ef4ae791cd2)

**Reply by kaixxx** [reply]
@JB-FHE It seems as if v 0.6 is not using CUDA at all in your case. 
Could you check in `config.yml` in `C:\Users<USERNAME>\AppData\Local\noScribe\noScribe` if both `pyannote_xpu` and `whisper_xpu` are set to `cuda`? 
I have implemented a fallback to the cpu and maybe your earlier experiment with the version without proper cuda support has changed this setting permanently.

**Reply by ems684** [reply]
Hi Kai, first: thank you so much for this transcription-tool which may rescue me in the progress of my masterthesis!

I have a problem and do not really know much about coding or AI or how to fix my problem, so maybe you or someone of the community can help me:

I installed the CUDA-version, the CUDA tool-kit and Microsoft Visual Studio (which was requested when I first installed the tool-kit).
Everything seems to work until the transcription starts. No transcript is to be seen even if I just try to transcribe two minutes.

The log file reads:
[Interview Kata.log](https://github.com/user-attachments/files/21604490/Interview.Kata.log)


I'm not shure if CUDA works the way it should or if something else might be the problem.

I have a NVIDIA GTX 1660 Ti which should work and in the config.yml pyannote_xpu and whisper_xpu are set to cuda.

I already thought about just installing the standard version of NoScribe but then why do I have this graphics card when I can not use it for this?!

Thanks in advance!

**Reply by kaixxx** [reply]
@ems684: I have heard about this problem before, with similar graphics cards. Please try version 0.6.1 of noScribe: https://drive.switch.ch/index.php/s/EIVup04qkSHb54j?path=%2FnoScribe%20vers.%200.6%2FWindows%2Fcuda

Please report back if it works. I might have unintentionally upgraded some libraries between 0.6.1 and 0.6.2 that broke support for some older NVIDIA cards. On my machine with a RTX 3060, 0.6.2 runs fine. 

(BTW, in your log file, you have clicked on "Abbrechen" [Cancel]. However, I think this wasn't the main problem.)

**Reply by ems684** [reply]
@kaixxx  Thank you so much! This seems to be working fine. I just tried it out with 2 min and now I am excited to see how fast it will be with the interviews which are about one to two hours long. I will keep you updated.

(With the newest version it didn't transcribe as I mentioned so after one hour or so I tried to cancel it and it didn't really do anything so I closed the task in the taskmanager. That is why there are so many "Abbrechen" in the log file :) )

**Comment by qualitywins** [comment]
0.6.2 works great for me.

with a rather old Quadro RTX 5000 mobil (RTX 2080 like) on a HP Zbook Die Schatzinsel took 139 Minutes ("with everything"). Before I processed a 2:06 hrs discussion in 17 Minutes. I assume memory speed is key again. Performance exceeds my expectation for certain on a 4 years old mobile workstation.

**Reply by kaixxx** [reply]
Nice. Good to hear that the RTX20XX cards are still fully functional. I had some trouble with the previous generation (RTX 1650 etc.) lately.

**Comment by kaixxx** [comment]
Hi

New beta versions of noScribe 0.7 are available here: https://drive.switch.ch/index.php/s/EIVup04qkSHb54j?path=%2FnoScribe%20vers.%200.7

It now includes batch transcription, a much wanted feature, and also a command line interface. Just run `noScribe -h`from the terminal to see the options. 

For CUDA support, a few smaller issues were resolved:
- Found a workaround for the problem the noScribe with CUDA was sometimes crashing after the transcript was finished.
- Fixed the issue that noScribe would get slower over time with long transcripts (this had to do with the logging on screen).

One problem remaining is that the support for the RTX 10XX generation of cards might be flaky. In order to support the newest RTX 50XX generation, I had to switch to PyTorch with CUDA 12.8. This should officially still support RTX 10XX cards, but I have heard about crashes during the transcription phase. Make sure that your NVIDIA drivers are on version 570.65 or higher and that you have an up to date CUDA toolkit installed.

Please try it out! It would be great to get some feedback before the final release.

**Reply by Evenzotesten** [reply]
:) batch transcription.. thank you! I will test 0.7 soon! Come back with feedback.

**Reply by Evenzotesten** [reply]
I just did a run with beta 0.7 @kaixxx . :) CUDA now is fully supported on my NVIDIA (whole process from speaker identification till whisper ai). (yes issue on 0.6.2). A video of 4 hours and 45 minutes is transcript to VTT in 20 minutes and 2 seconds .. CUDA almost continue on 90%+ CPU. I did not check the quality of the VTT and also no yet checked the batch functionality... will do that soon.. but i am very happy with the correct use of CUDA on my NVIDIA :) 

https://github.com/user-attachments/assets/4b4f1829-58d7-496b-b8fd-bc55f01d3924

![noscribetest07_cuda](https://github.com/user-attachments/assets/af44111c-bbde-40fa-8795-00e77063d708)

**Comment by paskima** [comment]
THANK YOU ALL!

<img width="1281" height="1203" alt="Bildschirmfoto_20250930_094611" src="https://github.com/user-attachments/assets/020531bc-46a0-4619-8d0c-4e59f1a429e7" />Awsome! Die Schatzinsel needs 17:11 including Speaker Detection on _Nobara LINUX (rtx 4090) even the GPU was not over 50%!!! On Windows it works good also (>20min without Speaker Detection, GPU >90%, 4070)... 
Earlier I just started more instances, for different interviews an let them transcribed at the same time. So batch was not on my wish list but its nice to have, also I don't have to name the target everytime, that is awsome. 

Several (small) Things: 
- For 0.7 on Linux I had to copy the icon from the old instance to get it to work. (If anybody else fails)
- it crashed often during transcription on _Auto Language_ (win and linux!) But its ends and open the editor with the text already transcribed (real good solution) . I didn't figure out the problem yet.

**Reply by kaixxx** [reply]
Thank you for testing, nice to hear that it works so well. 
- Can you tell me more about the icon: which file was copied to which folder? I would like to fix this for the release.
- Regarding the crashes: Please take a look into the log files in `~/noScribe/noScribe/log`. Do you get more information about the crashes, e.g., a traceback? I doubt that Auto Language is the culprit. Once you get the message "Language XX was detected..." on screen, the automatic language detection is finished and everything runs exactly the same as if you would have selected this language in the first place.

**Reply by kaixxx** [reply]
>  But its ends and open the editor with the text already transcribed (real good solution) 

Actually, I have changed this behavior now, so that the editor only opens if the transcription has been finished without errors. Otherwise, people might not realize that there was an error and the transcript is incomplete (especially with very long texts). However, I made sure that you can still open the partial transcript (if available) manually via the transcription queue list. 

See https://github.com/kaixxx/noScribe/commit/e39174747cee1ad95ff80a97456bc452b8e8964e and https://github.com/kaixxx/noScribe/commit/95598a313616856bfc31ae2cf5d29ccee25998aa

**Comment by paskima** [comment]
Thanks for reacting fast!
1) At Linux _internal/noScribeLogo is missing ( _tkinter.TclError: couldn't
open "/home/paskima/noScribe/_internal/noScribeLogo.png")
At Nobara Linux I had to install cuda/cudnn with the package manager, it
could'nt be find while transcribing, just as an info
result: Die Schatzinsel speaker detected and transcribed in <24 min !

2) At Windows Log says  "... [03:53:30] ...  (..) Endlich kam die Brise und
ich fühlte das Kabel wieder schlaff werden und schlug mit einem kräftigen
Hieb die beiden letzten Stränge durch.ERROR: Transcription worker exited
unexpectedly (code 3221226505)." No more hints, difficult to reproduce,
till now it just happens at "Die Schatzinsel" !?

Am Di., 30. Sept. 2025 um 19:02 Uhr schrieb kaixxx ***@***.***

**Reply by kaixxx** [reply]
Thank you. Do you get this error always with "Die Schatzinsel"? I have tried it, and it works fine for me (Windows, RTX 3060 12GB, 27:49 minutes including speaker detection).

**Reply by gernophil** [reply]
Thanks for the info about the missing icon in Linux. This is probably a path mismatch. About installing cuda/cudnn, this is normal and can't be shipped as far as I know, but we should mention it in the manual.

**Reply by kaixxx** [reply]
@gernophil, @paskima : There is an open PR with improved Linux installation instructions: https://github.com/kaixxx/noScribe/pull/219 Could you take a look? I have not enough experience with Linux.

**Reply by gernophil** [reply]
I'll take a detailed look at this tomorrow. It seems the PR is mostly about installing noScribe from source. The current instructions have some minor flaws, but it seems @paskima is installing the binary anyway. I can take a look tomorrow :).

**Reply by gernophil** [reply]
About the .png error. This is probably due to these lines:
```
        if platform.system() == "Linux":
            if hasattr(sys, "_MEIPASS"):
                self.iconphoto(True, tk.PhotoImage(file=os.path.join(sys._MEIPASS, "noScribeLogo.png")))
            else:
                self.iconphoto(True, tk.PhotoImage(file='noScribeLogo.png'))
```
I don't add the file `noScribeLogo.png` to the Linux binary, but I also don't use it for macOS. The corresponding line for macOS would be:
```
        if platform.system() in ("Darwin", "Windows"):
            self.iconbitmap(os.path.join(app_dir, 'noScribeLogo.ico'))
```
Easiest would probably be to also switch to `noScribeLogo.ico` for Linux. Do you know, what the icon is used for in this part of the code, @kaixxx?

**Reply by gernophil** [reply]
@paskima, could you verify that you are using the pre-compiled Linux version? I'm having trouble to run this on Fedora. Maybe everyone has to build it on it's own unfortunately, if the Linux distros differ too much.

**Reply by paskima** [reply]
> @paskima, could you verify that you are using the pre-compiled Linux version? I'm having trouble to run this on Fedora. Maybe everyone has to build it on it's own unfortunately, if the Linux distros differ too much.

Yes, older pre-compiled 0.7 on Nobara! (modified Feudora) Works like glove. Tower, Bios deactivated onboard GPU.

**Reply by paskima** [reply]
> > @paskima, could you verify that you are using the pre-compiled Linux version? I'm having trouble to run this on Fedora. Maybe everyone has to build it on it's own unfortunately, if the Linux distros differ too much.
> 
> Yes, older pre-compiled 0.7 on Nobara! Works like glove. Desktop, Bios deactivated onboard GPU.

(had to deactivate onboard GPU for Hogwarts Legacy)
