### ISSUE TITLE
Issue with NoScribe: PyAnnote error

### ISSUE THREAD

**Issue by PierreScht** [kaixxx/noScribe#170]
Hello,

I'm reaching out here because I can't get noscribe to work on my computer. Even though I have an NVIDIA graphics card, it's not powerful enough to run the CUDA version. So I installed the regular version, but that doesn't work either. Here's the error I get:
"Identification des locuteurs en cours...
Chargement de pyannote
PyAnnote error: Torch not compiled with CUDA enabled

Erreur à l'étape 2 - identification des locuteurs."

Thank you in advance for your help!

**Comment by kaixxx** [comment]
Hello,
it seems noScribe is still trying to use CUDA because it was installed previously on your machine. This is a bug, the non-CUDA-version should reset this setting. But you can also do this manually: 
- Go to the directory C:\Users\YOUR USERNAME\AppData\Local\noScribe\noScribe\. Note that "AppData" is a hidden folder, try googling on how to make them visible in the Explorer if needed.
- Open the file config.yml in the above folder and set the values for `pyannote_xpu` and `whisper_xpu` to `cpu`. Make sure that noScribe is closed while doing this, or your changes will be overridden. 
- Save the file and restart noScribe. It should now use your CPU, not CUDA.

**Comment by PierreScht** [comment]
Thank you, it works now!

**Comment by kaixxx** [comment]
I have improved the cuda detection a lot with version 0.7. Hopefully, this issue is now resolved completely.
