### ISSUE TITLE
"PyAnnote error:   Torch not compiled with CUDA enabled"

### ISSUE THREAD

**Issue by SecNotice** [kaixxx/noScribe#79]
"PyAnnote error:   Torch not compiled with CUDA enabled"

**Comment by gernophil** [comment]
Information not sufficient

**Comment by Vidda92** [comment]
I think I'm dealing with a similar issue, so I can give a bit more context:

I downloaded the non cuda Version of noScribe. After chosing the audio and the transcript file, noScribe will start the "Audioumwandlung", which is successful (I'm using the German version and don't know the English equivalent).

The error message occurs during speaker identification. After loading pyannote, it says "PyAnnote error:   Torch not compiled with CUDA enabled" aswell as "Fehler im 2. Schritt - Erkennung der Sprecher:innen"

In case the audio file itself might be the problem: The audio file I'm using at this moment is just a couple seconds long, but it contains little to no background noise and a single speaker. However I don't think the audio file itself is the problem because I ran into this issue with different audio files.

Thanks in advance!

**Comment by kaixxx** [comment]
Thank you for the information. I now remember that the same issue was discussed here: https://github.com/kaixxx/noScribe/discussions/65#discussioncomment-9843321
Please follow my suggestion there and change the values in "config.yml". Does this help?

**Comment by Odrec** [comment]
I'm having the same issue. We installed the non-Cuda version on Windows and I'm getting this error. I searched for a config.yaml file. There are two of them but neither of them have those options you mentioned.

One config.yaml file is in pyannote/audio/cli/evaluate_config/ and the other in pyannote/audio/cli/train_config/

**Comment by Vidda92** [comment]
First of all, thank you for your quick response! I wasn't aware of the other thread discussing the same problem.

I tried opening "config.yaml", but I couldn't find "pyannote_xpu" and "whisper_xpu" to change it to "cpu". Did I open the wrong file?

This is what I see when I open the file:

model: ???
protocol: ???
warm_up: 0.0
subset: test

defaults:
  - hydra: default
  
  Thanks again for your help!

**Comment by kaixxx** [comment]
This ist the wrong config file. Check the path that @gernophil posted above. It's also ".yml", not ".yaml".

**Comment by gernophil** [comment]
It looks like noScribe would like to use CUDA, which would be a huge speed improvement. Maybe try and download the CUDA version of noScribe.

**Comment by kaixxx** [comment]
> Now that I opened the right file, it worked!

Perfect, nice to hear. 
There is also a small bug here since noScribe should not try to use CUDA if is wasn't installed. I'll have to look into this and leave this issue open as a reminder.

**Comment by kaixxx** [comment]
> But it would only select cuda, if it would be possible to use it, wouldn't it?

It checks for the hardware, but not if the installed software stack is ready for CUDA. This is the bug I meant.

**Comment by MonikaBarget** [comment]
I had the same issue and will try your fixes. I was wondering, however, why this problem also occurs when I turn off speaker recognition.

**Comment by MonikaBarget** [comment]
> > Now that I opened the right file, it worked!
> 
> Perfect, nice to hear. There is also a small bug here since noScribe should not try to use CUDA if is wasn't installed. I'll have to look into this and leave this issue open as a reminder.

I think it would also be good to at least stop the program from aborting when the / an error occurs. I barely had time to read the error message because the program just crashed after the speaker identification failed. I then had to check the log files to see what was wrong, but I can tell you most of my colleagues would not know where to look...

**Comment by kaixxx** [comment]
I wasn't aware that noScribe crashes completely after this error. That's bad. I'll have to look into this.
@MonikaBarget : Can you tell me what the last entry in the logfile was before the crash?

**Comment by MonikaBarget** [comment]
> I wasn't aware that noScribe crashes completely after this error. That's bad. I'll have to look into this. @MonikaBarget : Can you tell me what the last entry in the logfile was before the crash?

I reinstalled noScribe just to be sure... So I lost the old logs. But it was something like:

```
ERROR: PyAnnote error: Torch not compiled with CUDA enabled
ERROR:
```
The line after the second `ERROR` was definitely empty like this. I got the same for all my test projects that crashed.

Now that I have updated the config.yml file, it works like a charm! Thanks so much for this great tool.

**Comment by kaixxx** [comment]
@MonikaBarget The error points to the fact that your hardware probably supports CUDA but you downloaded the non-CUDA version of noScribe. 
CUDA is a technology from NVIDIA that uses your graphics card to accelerate certain AI-related functions. It can save you a lot of time in noScribe. I would suggest installing the CUDA-enabled version of noScribe and reverting the settings in config.yml back to `pyannote_xpu: cpu`. 

I'm actually thinking about ditching the non-CUDA version altogether to avoid this error once and for all. The only advantage of the non-CUDA version ist the smaller download.

**Comment by MonikaBarget** [comment]
> @MonikaBarget The error points to the fact that your hardware probably supports CUDA but you downloaded the non-CUDA version of noScribe. CUDA is a technology from NVIDIA that uses your graphics card to accelerate certain AI-related functions. It can save you a lot of time in noScribe. I would suggest installing the CUDA-enabled version of noScribe and reverting the settings in config.yml back to `pyannote_xpu: cpu`.
> 
> I'm actually thinking about ditching the non-CUDA version altogether to avoid this error once and for all. The only advantage of the non-CUDA version ist the smaller download.

I have constant issues with storage on my work machine, which is, indeed, why I opted for the smaller download. I have asked our research software engineer, however, if there's an option to host noScribe on our Data Science Research Infrastructure.

**Comment by kaixxx** [comment]
@MonikaBarget OK, I understand. A client-server version of noScribe is in the making but not finished yet.

**Comment by Odrec** [comment]
> @MonikaBarget OK, I understand. A client-server version of noScribe is in the making but not finished yet. 

That sounds great!

**Comment by kaixxx** [comment]
@MonikaBarget Good you do me a favor? I've implemented a better CUDA-detection (hopefully). Problem is, I cannot really test it because I don't have a NVIDIA graphics card. It would be great if you could perfom the following steps:
- Download the newly compiled 'noScribe.exe' from here: https://drive.switch.ch/index.php/s/ThA8Z8zl4ZFvHQR
- Replace 'noScribe.exe' in you installation (C:\Program Files (x86)\noScribe) with the new exe. Keep the old exe somewhere save in case the new one doesn't work for some reason. 
- Delete or rename the config.yml
- Start noScribe, let it perfom a (short) transcription and close it again. 
- If everything works fine, a new config.yml should be created with the options for 'pyannote_xpu' and 'whisper_xpu' both set to 'cpu'.

**Comment by kaixxx** [comment]
@MonikaBarget **Please wait a moment with your test.** It seems that just swapping the exe doesn't work. I will compile a new installer. It's an automated process so no big deal, but it takes a while.

**Comment by MonikaBarget** [comment]
> @MonikaBarget **Please wait a moment with your test.** It seems that just swapping the exe doesn't work. I will compile a new installer. It's an automated process so no big deal, but it takes a while.

I will try it tomorrow! I am just running a transcription on a dictation and don't want to interrupt it now.

**Comment by kaixxx** [comment]
@MonikaBarget Ok, the new installer finished uploading: https://drive.switch.ch/index.php/s/0h0TU8ey55P7Nm8
- Install the new version
- Delete or rename the config.yml
- Start noScribe, let it perfom a (short) transcription and close it again.
- If everything works fine, a new config.yml should be created with the options for 'pyannote_xpu' and 'whisper_xpu' both set to 'cpu'.

**Comment by MonikaBarget** [comment]
> @MonikaBarget Ok, the new installer finished uploading: https://drive.switch.ch/index.php/s/0h0TU8ey55P7Nm8
> 
>     * Install the new version
> 
>     * Delete or rename the config.yml
> 
>     * Start noScribe, let it perfom a (short) transcription and close it again.
> 
>     * If everything works fine, a new config.yml should be created with the options for 'pyannote_xpu' and 'whisper_xpu' both set to 'cpu'.

It worked! See my post in the MAC thread.

**Comment by kaixxx** [comment]
@MonikaBarget Perfect, thank you for testing. I will now integrate this into the official installer.
